[package]
name = "lumi"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12.23", features = ["json", "blocking"] }
serde = "1.0.226"
serde_json = "1.0.145"
urlencoding = "2.1.3"
tokio = { version = "1.28.2", features = ["full"] }